import assert from "node:assert/strict"; import { once } from "node:events"; import { createServer } from "node:http"; import test from "node:test"; import { admitted, createWorldHandler } from "./server.js";
async function listen(server: ReturnType<typeof createServer>): Promise<string> { server.listen(0,"127.0.0.1"); await once(server,"listening"); const a=server.address(); assert.ok(a&&typeof a!=="string"); return `http://127.0.0.1:${a.port}`; }
async function request(hostBody: unknown, headers: Record<string,string> = {}): Promise<Response> { const host=createServer((_,res)=>{res.writeHead(201,{"content-type":"application/json"});res.end(JSON.stringify(hostBody));}); const origin=await listen(host); const relay=createWorldHandler({host:"127.0.0.1",port:0,buildVersion:"world-test",environment:"test",tunnelUrl:new URL(origin),tunnelAllowedOrigin:origin,callerServiceId:"knowhere-api-server",callerToken:"caller",callerBuild:"api-test",callerEnvironment:"test",tunnelToken:"tunnel",timeoutMs:100}); const base=await listen(relay); try{return await fetch(`${base}/v1/admissions`,{method:"POST",headers:{"content-type":"application/json","x-knowhere-service-id":"knowhere-api-server","x-knowhere-service-token":"caller","x-knowhere-protocol-version":"1.0.0","x-knowhere-build":"api-test","x-knowhere-environment":"test",...headers},body:'{"ticket":"opaque"}'});}finally{relay.closeAllConnections();host.closeAllConnections();relay.close();host.close();} }
const projection={protocolVersion:"1.0.0",sessionId:"s",characterId:"c",worldId:"w",expiresAt:"2099-08-01T00:00:00.000Z"};
test("handler relays strict admitted projection with configured caller identity",async()=>{const response=await request(projection);assert.equal(response.status,201);assert.deepEqual(await response.json(),projection);});
test("handler rejects missing or wrong caller identity",async()=>{assert.equal((await request(projection,{"x-knowhere-build":"wrong"})).status,403);assert.equal((await request(projection,{"x-knowhere-environment":"wrong"})).status,403);});
test("handler rejects malformed upstream success",async()=>{const response=await request({...projection,expiresAt:"bad"});assert.equal(response.status,503);});
test("admitted projection rejects an already expired lease",()=>{assert.equal(admitted({...projection,expiresAt:"2026-07-01T00:00:00.000Z"},new Date("2026-07-02T00:00:00.000Z")),null);});
test("handler readiness is unavailable without complete private configuration",async()=>{const server=createWorldHandler({host:"127.0.0.1",port:0,buildVersion:"test",tunnelUrl:null,callerToken:null,tunnelToken:null,timeoutMs:100});const base=await listen(server);try{assert.equal((await fetch(`${base}/v1/readiness`)).status,503);}finally{server.close();}});
